#NOTE: you won't typically have to change the following two lines!
metasheet: 'chips/metasheet.csv'
ref: "chips/ref.yaml"

#Tell us what assembly to use (!! MUST be defined in chips/ref.yaml !!)
assembly: hg19

#ALIGNER: if you want to use bowtie2, set your aligner as 'bwt2'
#OTHERWISE leave it as 'bwa' (default)
aligner: 'bwa'
#aligner: 'bwt2'

#path to folder used for calcualting on-target enrichment
enrichment_targets: 'ref_files/hg19/regions/states'

# DEFINE the samples- each sample should have a name, e.g. SAMPLE1
# and a path to the input file, e.g. data/sample1.fastq.gz
# VALID INPUTS: fastq, fastq.gz, bam
# NOTE: for PAIRED-END fastq/fastq.gz, give both pairs to the sample:
# SAMPLE_1_PE:
#   - data/sample1_pair1.fastq
#   - data/sample1_pair2.fastq
# WARNING: DO not mix Paired-END and Single-End samples!!!
# ALSO: having the string "rep" or '.' in your sample name will throw an ERROR
# '.' causes Rscripts chop off names; and it's used as replicate splitter
samples:
  K4_PS96_2:
    - /mnt/cfce-stor3/projects/freedman-lab/seq_rawdata/20230210_X202SC23012627-Z01-F001_chips/usftp21.novogene.com/01.RawData/K4_PS96_2/K4_PS96_2_CKDL230002906-1A_HMLFCDSX5_L1_2.fq.gz
    - /mnt/cfce-stor3/projects/freedman-lab/seq_rawdata/20230210_X202SC23012627-Z01-F001_chips/usftp21.novogene.com/01.RawData/K4_PS96_2/K4_PS96_2_CKDL230002906-1A_HMLFCDSX5_L1_1.fq.gz
  #etc...
